baseURL = "https://playerpathway-documentation.onrender.com/"
languageCode = "en-us"
title = "Player Pathway user guide"
theme = "docsy"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[menu]

  [[menu.main]]
    identifier = "Accounts"
    name = "Player Pathway user guide"
    pre = "<i class='fa fa-heart'></i>"
    url = "/Accounts/"
    weight = 20
	